clc;
clear all;
close all;
x=[6,4,3,7,8];
h=[1,2,3,4];
l=conv(x,h);
disp('linear convolution of x(n) and h(n) is= ');
disp(l);
subplot(2,1,1);stem(l);
title('linear convolution');
xlabel('n');
ylabel('l');
grid on;
c=cconv(x,h);
disp('circular convolution of x(n) and h(n) is= ');
disp(c);
subplot(2,1,2);
stem(c);
title('circular convolution');
xlabel('n');
ylabel('c');
grid on;
